kind: pipeline
name: CI
type : docker

trigger:
  branch:
    - main
    - develop
    - feature/*
  event:
    - push

volumes:
  - name: m2cache
    host:
      path: /volume1/m2cache
steps:

  - name: build
    image: maven:3-openjdk-17-slim
    volumes:
      - name: m2cache
        path: /root/.m2
    environment :
      DATASOURCE_DRIVER: org.postgresql.Driver
      DATASOURCE_URL: jdbc:postgresql://db:5432/sa_test_db
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
      SONAR_HOST :
        from_secret : SONAR_HOST
      SONAR_TOKEN :
        from_secret : SONAR_TOKEN
    commands:
      - mvn clean compile test-compile -B  --file pom.xml -s settings.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD
      - mvn pmd:check -B --file pom.xml -s settings.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD
      - mvn com.github.spotbugs:spotbugs-maven-plugin:check -Dspotbugs.xmlOutput=true -Dspotbugs.failOnError=true -Dspotbugs.includeTests=true  --file pom.xml -s settings.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD
      - mvn org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report sonar:sonar -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=ujar-org:basics-restful-bookstore -Dsonar.projectName=ujar-org:basics-restful-bookstore --batch-mode  --file pom.xml -s settings.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD
    when:
      branch:
        include:
          - feature/*
          - develop
          - main

  - name: publish-snapshot-package
    depends_on :
      - build
    image: maven:3-openjdk-17-slim
    volumes :
      - name : m2cache
        path : /root/.m2
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands:
      - mvn deploy -DskipTests=true -Dcheckstyle.skip=true -s settings.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD
    when:
      branch:
        include:
          - feature/*
          - develop
          - main

  - name: publish-release-package
    depends_on :
      - build
    image: maven:3-openjdk-17-slim
    volumes :
      - name : m2cache
        path : /root/.m2
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands:
      - mvn deploy -DskipTests=true -Dcheckstyle.skip=true -s settings.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD
    when:
      event: tag

  - name: docker-build-dev-image
    depends_on :
      - publish-snapshot-package
    image: plugins/docker
    settings:
      dockerfile: ./Dockerfile
      context: ./
      storage_driver: vfs
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: docker-registry.ujar.org/ujar/basics-restful-bookstore
      registry: docker-registry.ujar.org
      tags :
        - latest
    when:
      branch:
        include:
          - feature/*
          - develop
          - main

services:
  - name: db
    image: postgres:13.7
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sa_test_db
